apiVersion: v1
kind: Namespace
metadata:
  name: aurelio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: aurelio-volume
   namespace: aurelio
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   

---
apiVersion: v1
kind: Service
metadata:
  name: theiaide-servico
  namespace: aurelio
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: theiaide
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theiaide-deploy
  namespace: aurelio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theiaide
  template:
    metadata:
      labels:
        app: theiaide
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: aurelio-volume
        persistentVolumeClaim:
          claimName: aurelio-volume

      containers:
      - image: rishikoy/theiaide-full:1.0.0-SNAPSHOT
        name: theiaide-aurelio
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /home/project
          name: aurelio-volume
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entrada-theiaide-nginx
  namespace: aurelio
spec:
  ingressClassName: nginx
  rules:
  - host: aurelio.fevereiro.jac.bsb.br
    http:
      paths:
      - backend:
          service:
            name: theiaide-servico
            port:
              number: 80
        path: /
        pathType: Prefix
